spring:
  datasource:
    url: jdbc:mysql://learn1-mysql:3306/cloud_user?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: learn1-nacos:8848
      discovery:
        cluster-name: loli # 集群名称